# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate

services:
  backup:
    build:
      context: .
      args:
        ALPINE_VERSION: '3.16'
    env_file: .env
    environment:
      SCHEDULE: '@daily' # optional
      BACKUP_KEEP_DAYS: 7 # optional
